[package]
name = "todo-app-rs"
version = "0.0.1"
edition = "2021"
authors = [
    "jordan <jordan@butterwick.tech>"
]
readme = "./README.md"
license = "Unlicense"

[dependencies]
crossterm = "0.25.0"
