[package]
name = "todo-app-rs"
version = "0.1.0"
edition = "2021"
authors = [
    "jordan <jordan@butterwick.tech>"
]
readme = "./README.md"
license = "Unlicense"

[dependencies]
crossterm = "0.26.1"
